package events

const (
	AgentStarting                 = "agent.starting"
	AgentReady                    = "agent.ready"
	AgentStopping                 = "agent.stopping"
	AgentError                    = "agent.error"
	PersistenceDegraded           = "agent.persistence_degraded"
	PersistenceRecovered          = "agent.persistence_recovered"
	PrinterConnecting             = "printer.connecting"
	PrinterConnected              = "printer.connected"
	PrinterDisconnected           = "printer.disconnected"
	PrinterReconnectScheduled     = "printer.reconnect_scheduled"
	PrinterConnectionFailed       = "printer.connection_failed"
	PrinterEnabled                = "printer.enabled"
	PrinterDisabled               = "printer.disabled"
	PrinterConfigurationChanged   = "printer.configuration_changed"
	PrinterError                  = "printer.error"
	ConfigChanged                 = "config.changed"
	JobReceived                   = "job.received"
	JobAccepted                   = "job.accepted"
	JobDuplicateRecognized        = "job.duplicate_recognized"
	JobRejected                   = "job.rejected"
	JobTargetCancelled            = "job.target_cancelled"
	JobCancelled                  = "job.cancelled"
	PrintRunQueued                = "print_run.queued"
	PrintRunClaimed               = "print_run.claimed"
	PrintRunTransmissionStarted   = "print_run.transmission_started"
	PrintRunTransmitted           = "print_run.transmitted"
	PrintRunFailed                = "print_run.failed"
	PrintRunUncertain             = "print_run.uncertain"
	PrintRunRetryExhausted        = "print_run.retry_exhausted"
	PrintRunAutomaticRetryCreated = "print_run.automatic_retry_created"
	ManualReprintRequested        = "manual_reprint.requested"
	PrintRunCancelled             = "print_run.cancelled"
	PrintRunConfirmedPrinted      = "print_run.confirmed_printed"
	AuthDenied                    = "auth.denied"
	WebSocketServerConnected      = "websocket.server_client_connected"
	WebSocketServerDisconnected   = "websocket.server_client_disconnected"
	WebSocketOutboundConnected    = "websocket.outbound_connected"
	WebSocketOutboundDisconnected = "websocket.outbound_disconnected"
	WebSocketReconnectScheduled   = "websocket.outbound_reconnect_scheduled"
	WebSocketDeliveryFailed       = "websocket.delivery_failed"
	WebSocketEventDropped         = "websocket.event_dropped"
	WebSocketEventAcknowledged    = "websocket.event_acknowledged"
	WebSocketDeadLettered         = "websocket.delivery_dead_lettered"
)

// Deprecated source-compatible aliases are intentionally omitted. Pre-release
// callers must adopt the final vocabulary rather than carry dual event names.
