import { useMemo, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { AlertTriangle, ClipboardCopy, FlaskConical, Printer, RefreshCw, RotateCcw } from 'lucide-react'
import { toast } from 'sonner'
import { api, APIError, queryKeys } from '@/lib/api'
import { uid } from '@/lib/format'
import type { JobDetail } from '@/lib/types'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Checkbox } from '@/components/ui/checkbox'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from '@/components/ui/alert-dialog'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { JsonViewer, PageHeader, StatusBadge } from '@/components/shared'
import { useJobDialog } from '@/components/job-dialog'

type JobRequest = { jobId: string; template: string; data: Record<string, unknown>; printerIds: string[] }
type ReprintRequest = { reprintRequestId: string; printerIds: string[]; reason: string }

function sampleTicket() { return { orderNumber: `TEST-${new Date().toISOString().slice(11, 19).replaceAll(':', '')}`, createdAt: new Date().toISOString(), items: [{ name: 'Tortilla española', quantity: 2, notes: 'Una sin cebolla' }, { name: 'Patatas bravas', quantity: 1 }, { name: 'Café con leche', quantity: 1, notes: 'Sin azúcar' }] } }

export default function POSSimulatorPage() {
  const queryClient = useQueryClient(); const { openJob } = useJobDialog()
  const status = useQuery({ queryKey: queryKeys.status, queryFn: ({ signal }) => api.status(signal), refetchInterval: 2000 })
  const [jobId, setJobId] = useState(() => uid('dashboard:kitchen:')); const [json, setJson] = useState(() => JSON.stringify(sampleTicket(), null, 2)); const [printers, setPrinters] = useState<Set<string>>(new Set())
  const [lastRequest, setLastRequest] = useState<JobRequest | null>(null); const [activeUid, setActiveUid] = useState(''); const [result, setResult] = useState<unknown>('No requests yet.'); const [statusText, setStatusText] = useState('Sample kitchen ticket loaded.')
  const [confirmNew, setConfirmNew] = useState<JobRequest | null>(null); const [reprintTargets, setReprintTargets] = useState<Set<string>>(new Set()); const [reprintId, setReprintId] = useState(() => uid('dashboard:reprint:')); const [reprintReason, setReprintReason] = useState(''); const [confirmReprint, setConfirmReprint] = useState<ReprintRequest | null>(null); const [lastReprint, setLastReprint] = useState<ReprintRequest | null>(null)
  const active = useQuery({ queryKey: queryKeys.job(activeUid), queryFn: ({ signal }) => api.job(activeUid, signal), enabled: !!activeUid, refetchInterval: activeUid ? 2000 : false })
  const configured = useMemo(() => status.data?.printers || [], [status.data?.printers])
  const effectivePrinters = useMemo(() => printers.size ? printers : new Set(configured.length ? [configured.find(item => item.printer.enabled)?.printer.id || configured[0].printer.id] : []), [configured, printers])
  const buildRequest = (): JobRequest => { if (!jobId.trim()) throw new Error('Job ID is required'); if (!effectivePrinters.size) throw new Error('Select at least one printer'); let data: unknown; try { data = JSON.parse(json) } catch (error) { throw new Error(`Ticket data is not valid JSON: ${error instanceof Error ? error.message : ''}`) } if (!data || typeof data !== 'object' || Array.isArray(data)) throw new Error('Ticket data must be a JSON object'); return { jobId: jobId.trim(), template: 'kitchen-ticket', data: data as Record<string, unknown>, printerIds: [...effectivePrinters] } }
  const submit = useMutation({ mutationFn: ({ request }: { request: JobRequest; mode: 'new' | 'duplicate' | 'conflict' }) => api.mutate<JobDetail>('/jobs', 'POST', request), onSuccess: async (response, variables) => { setResult(response); setConfirmNew(null); if (variables.mode === 'conflict') { setStatusText('Conflict probe was unexpectedly accepted and may have printed.'); toast.error('Conflict probe unexpectedly accepted') } else { setLastRequest(structuredClone(variables.request)); setActiveUid(response.uid); setStatusText(response.duplicate ? 'Duplicate request returned the existing Job; nothing new was queued.' : 'Kitchen ticket accepted and queued.'); toast.success(response.duplicate ? 'Duplicate request deduplicated' : 'Kitchen ticket queued') } await Promise.all([queryClient.invalidateQueries({ queryKey: ['jobs'] }), queryClient.invalidateQueries({ queryKey: ['queue'] })]) }, onError: (error, variables) => { const expected = variables.mode === 'conflict' && error instanceof APIError && error.status === 409; setResult({ code: error instanceof APIError ? error.code : '', error: error.message }); setStatusText(expected ? `Expected idempotency conflict: ${error.message}` : error.message); if (expected) toast.success('Idempotency conflict verified'); else toast.error(error.message) } })
  const originalExists = async () => { if (!activeUid) return false; try { await api.job(activeUid); return true } catch (error) { setStatusText('The original Job is no longer available, so the probe was not sent; it could print again.'); toast.error(error instanceof Error ? error.message : 'Job unavailable'); return false } }
  const probeDuplicate = async () => { if (lastRequest && await originalExists()) submit.mutate({ request: structuredClone(lastRequest), mode: 'duplicate' }) }
  const probeConflict = async () => { if (!lastRequest || !await originalExists()) return; const changed = structuredClone(lastRequest); changed.data.orderNumber = `${String(changed.data.orderNumber || '')}-CHANGED`; submit.mutate({ request: changed, mode: 'conflict' }) }
  const reprint = useMutation({ mutationFn: (request: ReprintRequest) => api.mutate<JobDetail>(`/jobs/${encodeURIComponent(activeUid)}/reprint`, 'POST', request), onSuccess: async (response, request) => { setResult(response); setLastReprint(structuredClone(request)); setConfirmReprint(null); toast.success(response.duplicate ? 'Duplicate reprint deduplicated' : 'Reprint queued'); await Promise.all([active.refetch(), queryClient.invalidateQueries({ queryKey: ['jobs'] }), queryClient.invalidateQueries({ queryKey: ['queue'] })]) }, onError: error => { setResult({ error: error.message }); toast.error(error.message) } })
  const requestReprint = () => { if (!active.data || !reprintTargets.size) return toast.error('Select at least one active-Job target'); if (!reprintId.trim()) return toast.error('Reprint request ID is required'); setConfirmReprint({ reprintRequestId: reprintId.trim(), printerIds: [...reprintTargets], reason: reprintReason.trim() }) }
  const uncertain = active.data?.originalPrinters.some(target => reprintTargets.has(target.printerId) && target.runs?.some(run => run.status === 'uncertain' && !run.resolution))
  return <><PageHeader title="POS Simulator" description="Exercise real kitchen-ticket Jobs, idempotency, and reprints from the local dashboard." />
    <div className="mb-4 flex items-start gap-3 rounded-xl border border-amber-500/40 bg-amber-500/10 p-4 text-sm text-amber-800 dark:text-amber-200"><AlertTriangle className="size-5 shrink-0" />Submitting Jobs and reprints can produce physical tickets. Verify selected printers before confirming.</div>
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><FlaskConical className="size-4" />Create kitchen ticket</CardTitle><CardDescription>Select printers and submit immutable template data.</CardDescription></CardHeader><CardContent className="space-y-4"><div><div className="mb-2 flex items-center gap-2"><Checkbox checked={configured.length > 0 && effectivePrinters.size === configured.length} onCheckedChange={checked => setPrinters(checked === true ? new Set(configured.map(item => item.printer.id)) : new Set())} id="dev-all-printers" /><Label htmlFor="dev-all-printers">Select all printers</Label></div><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{configured.map(item => <Label key={item.printer.id} className="flex cursor-pointer items-start gap-3 rounded-xl border p-3 has-[[data-checked]]:border-primary"><Checkbox checked={effectivePrinters.has(item.printer.id)} onCheckedChange={checked => setPrinters(() => { const base = new Set(effectivePrinters); if (checked === true) base.add(item.printer.id); else base.delete(item.printer.id); return base })} /><span><span className="flex items-center gap-2 font-medium">{item.printer.displayName}<StatusBadge value={item.state} /></span><span className="text-xs text-muted-foreground">{item.printer.id} · queue {item.queueDepth}</span></span></Label>)}</div></div>
      <div className="space-y-2"><Label htmlFor="dev-job-id">Job ID</Label><div className="flex gap-2"><Input id="dev-job-id" value={jobId} onChange={event => setJobId(event.target.value)} /><Button variant="outline" onClick={() => setJobId(uid('dashboard:kitchen:'))}>Generate new</Button></div></div>
      <div className="space-y-2"><Label htmlFor="dev-data">Ticket data (JSON)</Label><Textarea id="dev-data" rows={14} className="font-mono text-xs" value={json} onChange={event => setJson(event.target.value)} /></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => { setJson(JSON.stringify(sampleTicket(), null, 2)); setStatusText('Sample kitchen ticket loaded.') }}><RotateCcw />Reset sample</Button><Button onClick={() => { try { setConfirmNew(buildRequest()) } catch (error) { toast.error(error instanceof Error ? error.message : 'Invalid request') } }}><Printer />Submit and print</Button><Button variant="outline" disabled={!lastRequest || submit.isPending} onClick={probeDuplicate}><ClipboardCopy />Resubmit exact request</Button><Button variant="outline" disabled={!lastRequest || submit.isPending} onClick={probeConflict}>Test changed-data conflict</Button></div><p className="text-sm text-muted-foreground">{statusText}</p></CardContent></Card>
    {active.data && <Card className="mt-4"><CardHeader><CardTitle>Active test Job</CardTitle><CardDescription className="flex flex-wrap items-center gap-2">{active.data.jobId} · <span className="font-mono">{active.data.uid}</span> · <StatusBadge value={active.data.state} /> · {active.data.fulfilledPrinterCount}/{active.data.originalPrinterCount} fulfilled</CardDescription></CardHeader><CardContent className="space-y-4"><div className="flex gap-2"><Button variant="outline" onClick={() => active.refetch()}><RefreshCw />Refresh</Button><Button variant="outline" onClick={() => openJob(active.data.uid)}>Open full controls</Button></div>
      <div className="space-y-3">{active.data.originalPrinters.map(target => <div key={target.printerId} className="overflow-x-auto rounded-xl border"><div className="flex items-center justify-between bg-muted/40 p-3"><Label className="flex items-center gap-2"><Checkbox checked={reprintTargets.has(target.printerId)} onCheckedChange={checked => setReprintTargets(previous => { const next = new Set(previous); if (checked === true) next.add(target.printerId); else next.delete(target.printerId); return next })} />{target.printerId}</Label><StatusBadge value={target.fulfilled ? 'fulfilled' : target.cancelled ? 'cancelled' : 'unfulfilled'} /></div><Table><TableHeader><TableRow><TableHead>#</TableHead><TableHead>Run UID</TableHead><TableHead>Trigger</TableHead><TableHead>Status</TableHead><TableHead>Bytes</TableHead><TableHead>Error</TableHead></TableRow></TableHeader><TableBody>{target.runs?.map(run => <TableRow key={run.uid}><TableCell>{run.runNumber}</TableCell><TableCell className="font-mono text-xs">{run.uid}</TableCell><TableCell>{run.trigger}</TableCell><TableCell><StatusBadge value={run.status} /></TableCell><TableCell>{run.bytesAccepted}</TableCell><TableCell>{run.errorMessage || '—'}</TableCell></TableRow>)}</TableBody></Table></div>)}</div>
      <div className="grid gap-3 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="dev-reason">Reason (optional)</Label><Input id="dev-reason" value={reprintReason} onChange={event => setReprintReason(event.target.value)} /></div><div className="space-y-2"><Label htmlFor="dev-reprint-id">Reprint request ID</Label><div className="flex gap-2"><Input id="dev-reprint-id" value={reprintId} onChange={event => setReprintId(event.target.value)} /><Button variant="outline" onClick={() => setReprintId(uid('dashboard:reprint:'))}>New</Button></div></div></div><div className="flex gap-2"><Button onClick={requestReprint} disabled={!reprintTargets.size}><Printer />Reprint selected</Button><Button variant="outline" disabled={!lastReprint} onClick={() => lastReprint && setConfirmReprint(structuredClone(lastReprint))}>Repeat same request</Button></div>
    </CardContent></Card>}
    <Card className="mt-4"><CardHeader><CardTitle>Last API result</CardTitle></CardHeader><CardContent><JsonViewer value={result} /></CardContent></Card>
    <AlertDialog open={!!confirmNew} onOpenChange={open => !open && !submit.isPending && setConfirmNew(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Submit this kitchen ticket?</AlertDialogTitle><AlertDialogDescription>This may produce physical output on {confirmNew?.printerIds.join(', ')}.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Back</AlertDialogCancel><AlertDialogAction disabled={!confirmNew || submit.isPending} onClick={() => confirmNew && submit.mutate({ request: confirmNew, mode: 'new' })}>{submit.isPending ? 'Submitting…' : 'Submit and print'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
    <AlertDialog open={!!confirmReprint} onOpenChange={open => !open && !reprint.isPending && setConfirmReprint(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Create physical reprints?</AlertDialogTitle><AlertDialogDescription>{uncertain ? 'An earlier result is uncertain and may already have printed. ' : ''}This creates {confirmReprint?.printerIds.length || 0} new physical Print Run(s).</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Back</AlertDialogCancel><AlertDialogAction disabled={!confirmReprint || reprint.isPending} onClick={() => confirmReprint && reprint.mutate(confirmReprint)}>{reprint.isPending ? 'Submitting…' : 'Create reprints'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </>
}
