import { useEffect, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { KeyRound, RadioTower, Save, Trash2 } from 'lucide-react'
import { toast } from 'sonner'
import { api, queryKeys } from '@/lib/api'
import { formatDate } from '@/lib/format'
import type { PairingCode, TokenInfo, WebSocketSettings } from '@/lib/types'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from '@/components/ui/alert-dialog'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { ErrorState, LoadingState, PageHeader } from '@/components/shared'

export default function POSPairingPage() {
  const queryClient = useQueryClient(); const [origin, setOrigin] = useState(''); const [code, setCode] = useState<PairingCode | null>(null); const [revoke, setRevoke] = useState<TokenInfo | null>(null)
  const [wsMode, setWsMode] = useState<WebSocketSettings['mode']>('disabled'); const [wsEndpoint, setWsEndpoint] = useState(''); const [wsSecretRef, setWsSecretRef] = useState(''); const [wsOrigins, setWsOrigins] = useState(''); const [eventToken, setEventToken] = useState('')
  const settings = useQuery({ queryKey: [...queryKeys.pairing, 'settings'], queryFn: ({ signal }) => api.settings(signal) })
  const tokens = useQuery({ queryKey: [...queryKeys.pairing, 'tokens'], queryFn: ({ signal }) => api.tokens(signal) })
  const websocket = useQuery({ queryKey: [...queryKeys.pairing, 'websocket'], queryFn: ({ signal }) => api.websocketSettings(signal) })
  useEffect(() => { if (settings.data) setOrigin(settings.data.allowedOrigin || '') }, [settings.data])
  useEffect(() => { if (websocket.data) { setWsMode(websocket.data.mode); setWsEndpoint(websocket.data.destination?.endpoint || ''); setWsSecretRef(websocket.data.destination?.secretRef || ''); setWsOrigins(websocket.data.allowedOrigins.join(', ')) } }, [websocket.data])
  useEffect(() => { if (!code) return; const delay = Math.max(0, new Date(code.expiresAt).getTime() - Date.now()); const timer = window.setTimeout(() => setCode(null), delay); return () => window.clearTimeout(timer) }, [code])
  const save = useMutation({ mutationFn: () => api.mutate('/admin/settings', 'PUT', { allowedOrigin: origin.trim() }), onSuccess: () => { toast.success('Allowed origin saved'); queryClient.invalidateQueries({ queryKey: queryKeys.pairing }) }, onError: error => toast.error(error.message) })
  const generate = useMutation({ mutationFn: api.pairingCode, onSuccess: result => { setCode(result); toast.success('Code valid for five minutes') }, onError: error => toast.error(error.message) })
  const revokeToken = useMutation({ mutationFn: (id: string) => api.mutate(`/admin/tokens/${encodeURIComponent(id)}`, 'DELETE'), onSuccess: () => { toast.success('Token revoked'); setRevoke(null); queryClient.invalidateQueries({ queryKey: queryKeys.pairing }) }, onError: error => toast.error(error.message) })
  const saveWebsocket = useMutation({ mutationFn: () => { if (!websocket.data) throw new Error('WebSocket settings are unavailable'); const client = wsMode === 'client' || wsMode === 'both'; return api.mutate<WebSocketSettings>('/admin/websocket', 'PUT', { ...websocket.data, mode: wsMode, allowedOrigins: wsOrigins.split(',').map(value => value.trim()).filter(Boolean), destination: client ? { ...(websocket.data.destination || { id: 'primary', categories: ['agent', 'printer', 'job', 'print_run', 'config'], connectTimeoutMs: 10000, heartbeatMs: 20000, staleTimeoutMs: 60000, writeTimeoutMs: 10000, reconnectMinMs: 2000, reconnectMaxMs: 60000, reconnectJitter: 0.2, ackTimeoutMs: 30000, outboundQueueCapacity: 512 }), enabled: true, endpoint: wsEndpoint.trim(), authType: wsSecretRef.trim() ? 'bearer' : 'none', secretRef: wsSecretRef.trim() } : undefined }) }, onSuccess: () => { toast.success('WebSocket settings saved; restart the agent to apply them'); queryClient.invalidateQueries({ queryKey: queryKeys.pairing }) }, onError: error => toast.error(error.message) })
  const createEventToken = useMutation({ mutationFn: () => api.mutate<{ token: string }>('/admin/event-credentials', 'POST', { label: 'Dashboard-created event consumer' }), onSuccess: result => { setEventToken(result.token); toast.success('Event credential created; copy it now') }, onError: error => toast.error(error.message) })
  return <><PageHeader title="POS Pairing" description="Authorize a hosted POS origin to submit Jobs to this local agent." />
    {(settings.isLoading || tokens.isLoading) && <LoadingState rows={3} />}{settings.isError && <ErrorState error={settings.error} retry={() => settings.refetch()} />}
    <div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle className="flex items-center gap-2"><RadioTower className="size-4" />Allowed POS origin</CardTitle><CardDescription>Exact HTTP(S) origin of the hosted POS page.</CardDescription></CardHeader><CardContent className="space-y-3"><Label htmlFor="pos-origin">Origin</Label><Input id="pos-origin" placeholder="https://pos.example.com" value={origin} onChange={event => setOrigin(event.target.value)} /><Button onClick={() => save.mutate()} disabled={save.isPending}><Save />{save.isPending ? 'Saving…' : 'Save origin'}</Button></CardContent></Card>
      <Card><CardHeader><CardTitle className="flex items-center gap-2"><KeyRound className="size-4" />One-time pairing code</CardTitle><CardDescription>Enter this code in the POS setup screen within five minutes.</CardDescription></CardHeader><CardContent className="space-y-3"><Button onClick={() => generate.mutate()} disabled={generate.isPending}>Generate pairing code</Button>{code && <div className="rounded-xl border bg-muted/40 p-5 text-center"><p className="font-mono text-4xl font-bold tracking-[.3em]">{code.code}</p><p className="mt-2 text-xs text-muted-foreground">Expires {formatDate(code.expiresAt)}</p></div>}</CardContent></Card>
    </div>
    <Card className="mt-4"><CardHeader><CardTitle>Client tokens</CardTitle><CardDescription>Only token metadata is shown. Clear token values are never retained.</CardDescription></CardHeader><CardContent className="overflow-x-auto px-0 pb-0"><Table><TableHeader><TableRow><TableHead>Label</TableHead><TableHead>Origin</TableHead><TableHead>Created</TableHead><TableHead>Last used</TableHead><TableHead /></TableRow></TableHeader><TableBody>{tokens.data?.map(token => <TableRow key={token.id}><TableCell>{token.label}</TableCell><TableCell>{token.allowedOrigin}</TableCell><TableCell>{formatDate(token.createdAt)}</TableCell><TableCell>{formatDate(token.lastUsedAt)}</TableCell><TableCell>{token.revoked ? <span className="text-muted-foreground">Revoked</span> : <Button variant="destructive" size="sm" onClick={() => setRevoke(token)}><Trash2 />Revoke</Button>}</TableCell></TableRow>)}{tokens.data && !tokens.data.length && <TableRow><TableCell colSpan={5} className="text-center text-muted-foreground">No tokens issued</TableCell></TableRow>}</TableBody></Table></CardContent></Card>
    <Card className="mt-4"><CardHeader><CardTitle>Real-time WebSocket events</CardTitle><CardDescription>Replayable server streaming and acknowledged outbound reporting. Remote commands are never accepted.</CardDescription></CardHeader><CardContent className="grid gap-3 md:grid-cols-2"><div className="space-y-2"><Label htmlFor="ws-mode">Mode</Label><select id="ws-mode" className="h-9 w-full rounded-md border bg-transparent px-3 text-sm" value={wsMode} onChange={event => setWsMode(event.target.value as WebSocketSettings['mode'])}><option value="disabled">Disabled</option><option value="server">Server</option><option value="client">Client</option><option value="both">Both</option></select></div>{(wsMode === 'server' || wsMode === 'both') && <div className="space-y-2"><Label htmlFor="ws-origins">Allowed browser origins</Label><Input id="ws-origins" placeholder="https://ops.example.com" value={wsOrigins} onChange={event => setWsOrigins(event.target.value)} /></div>}{(wsMode === 'client' || wsMode === 'both') && <><div className="space-y-2"><Label htmlFor="ws-endpoint">Outbound endpoint</Label><Input id="ws-endpoint" placeholder="wss://events.example.com/agent" value={wsEndpoint} onChange={event => setWsEndpoint(event.target.value)} /></div><div className="space-y-2"><Label htmlFor="ws-secret">Credential reference</Label><Input id="ws-secret" placeholder="env:PRINT_AGENT_WS_TOKEN" value={wsSecretRef} onChange={event => setWsSecretRef(event.target.value)} /></div></>}<div className="flex items-end"><Button onClick={() => saveWebsocket.mutate()} disabled={!websocket.data || saveWebsocket.isPending}><Save />Save WebSocket settings</Button></div><div className="md:col-span-2 border-t pt-3"><Button variant="outline" onClick={() => createEventToken.mutate()} disabled={createEventToken.isPending}><KeyRound />Create server event credential</Button>{eventToken && <div className="mt-3 rounded-md border bg-muted/40 p-3"><p className="text-xs text-muted-foreground">Copy now; this value is never shown again.</p><code className="break-all text-sm">{eventToken}</code></div>}</div></CardContent></Card>
    <AlertDialog open={!!revoke} onOpenChange={open => !open && setRevoke(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Revoke {revoke?.label}?</AlertDialogTitle><AlertDialogDescription>The POS client will immediately lose access and must be paired again.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Back</AlertDialogCancel><AlertDialogAction variant="destructive" disabled={!revoke || revokeToken.isPending} onClick={() => revoke && revokeToken.mutate(revoke.id)}>Revoke token</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </>
}
