import { useEffect, useMemo, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { ExternalLink, FileClock, Pencil, Plus, Power, Printer as PrinterIcon, RefreshCw, ScrollText, Settings, Trash2 } from 'lucide-react'
import { useNavigate, useSearchParams } from 'react-router'
import { toast } from 'sonner'
import { api, queryKeys } from '@/lib/api'
import { formatDate, formatTime } from '@/lib/format'
import type { PrinterConfig } from '@/lib/types'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from '@/components/ui/alert-dialog'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { EmptyState, ErrorState, LoadingState, PageHeader, StatusBadge } from '@/components/shared'
import { useJobDialog } from '@/components/job-dialog'

const selectClass = 'h-8 w-full rounded-lg border border-input bg-background px-2.5 text-sm outline-none focus:ring-2 focus:ring-ring/50'
type Editor = { editingId?: string; id: string; displayName: string; endpoint: string; deviceAddress: string; encoding: string; charactersPerLine: number }
const blankEditor = (endpoint = '', address = ''): Editor => ({ id: '', displayName: '', endpoint, deviceAddress: address, encoding: 'CP858', charactersPerLine: 32 })

function allRuns(queue?: Awaited<ReturnType<typeof api.queue>>) {
  if (!queue) return []
  const runs = [queue.processingRun, ...queue.queuedRuns, ...queue.retryPendingRuns, ...queue.attentionRuns, ...queue.recentTransmittedRuns].filter(Boolean)
  return [...new Map(runs.map(run => [run!.uid, run!])).values()]
}

export default function PrintersPage() {
  const [params, setParams] = useSearchParams(); const navigate = useNavigate(); const queryClient = useQueryClient(); const { openJob } = useJobDialog()
  const [editor, setEditor] = useState<Editor | null>(null); const [removeOpen, setRemoveOpen] = useState(false)
  const status = useQuery({ queryKey: queryKeys.status, queryFn: ({ signal }) => api.status(signal), refetchInterval: 2000 })
  const printerId = params.get('printerId') || ''; const detailTab = params.get('printerTab') || 'overview'
  const selected = status.data?.printers.find(item => item.printer.id === printerId)
  const candidates = useQuery({ queryKey: queryKeys.candidates, queryFn: ({ signal }) => api.candidates(signal), enabled: !!editor })
  const queue = useQuery({ queryKey: queryKeys.queue(printerId, 50), queryFn: ({ signal }) => api.queue(printerId, 50, signal), enabled: !!printerId && detailTab === 'queue', refetchInterval: 5000 })
  const detailLogParams = useMemo(() => new URLSearchParams({ limit: '20', printerId }), [printerId])
  const logs = useQuery({ queryKey: queryKeys.printerLogs(`detail:${printerId}`), queryFn: ({ signal }) => api.printerLogs(detailLogParams, signal), enabled: !!printerId && detailTab === 'logs', refetchInterval: 5000 })
  useEffect(() => {
    const endpoint = params.get('newEndpoint'); if (endpoint !== null && !editor) {
      setEditor(blankEditor(endpoint, params.get('deviceAddress') || '')); const next = new URLSearchParams(params); next.delete('newEndpoint'); next.delete('deviceAddress'); setParams(next, { replace: true })
    }
  }, [params, editor, setParams])
  useEffect(() => { if (printerId && status.data && !selected) { toast.error(`Printer ${printerId} was not found`); setParams({}, { replace: true }) } }, [printerId, selected, setParams, status.data])
  const invalidate = async () => Promise.all([queryClient.invalidateQueries({ queryKey: queryKeys.status }), queryClient.invalidateQueries({ queryKey: ['queue'] }), queryClient.invalidateQueries({ queryKey: ['printer-logs'] })])
  const action = useMutation({ mutationFn: ({ path, method = 'POST' }: { path: string; method?: string }) => api.mutate(path, method), onSuccess: () => invalidate(), onError: error => toast.error(error.message) })
  const save = useMutation({ mutationFn: (value: Editor) => api.savePrinter({ id: value.id, displayName: value.displayName || value.id, endpoint: value.endpoint, deviceAddress: value.deviceAddress, encoding: value.encoding, charactersPerLine: value.charactersPerLine }, value.editingId), onSuccess: async () => { toast.success('Printer saved'); setEditor(null); await invalidate() }, onError: error => toast.error(error.message) })
  const changeTab = (value: string) => {
    const next = new URLSearchParams(params)
    if (value === 'overview') next.delete('printerTab')
    else next.set('printerTab', value)
    setParams(next)
  }
  const closeDetail = () => { const next = new URLSearchParams(params); next.delete('printerId'); next.delete('printerTab'); setParams(next, { replace: true }) }
  const openEditor = (printer?: PrinterConfig) => setEditor(printer ? { editingId: printer.id, id: printer.id, displayName: printer.displayName, endpoint: printer.endpoint, deviceAddress: printer.deviceAddress || '', encoding: printer.encoding, charactersPerLine: printer.charactersPerLine } : blankEditor())
  const configuredCandidate = (endpoint: string) => candidates.data?.find(candidate => candidate.endpoint === endpoint)

  return <><PageHeader title="Printers" description="Configure printer identities, connections, rendering profiles, queues, and operational history." actions={<><Button onClick={() => openEditor()}><Plus />Add printer</Button><Button variant="outline" onClick={() => action.mutate({ path: '/printers/reconnect-all' })}><RefreshCw />Reconnect all</Button><Button variant="outline" onClick={() => action.mutate({ path: '/system/open-bluetooth-settings' })}><ExternalLink />Bluetooth settings</Button></>} />
    {status.isLoading && <LoadingState rows={4} />}{status.isError && <ErrorState error={status.error} retry={() => status.refetch()} />}
    {status.data && !status.data.printers.length && <EmptyState title="No printers configured" detail="Pair a Bluetooth device first, or add a printer from a discovered endpoint." action={<Button onClick={() => navigate('/setup/pair')}>Pair devices</Button>} />}
    <div className="grid gap-3">{status.data?.printers.map(item => <Card key={item.printer.id} className="cursor-pointer transition hover:border-primary/40" role="button" tabIndex={0} onClick={() => setParams({ printerId: item.printer.id })} onKeyDown={event => { if (event.key === 'Enter' || event.key === ' ') setParams({ printerId: item.printer.id }) }}>
      <CardHeader className="flex-row items-start justify-between gap-3"><div><CardTitle className="flex flex-wrap items-center gap-2"><PrinterIcon className="size-4" />{item.printer.displayName}<StatusBadge value={item.state} /></CardTitle><p className="mt-2 text-sm text-muted-foreground"><span className="font-medium text-foreground">{item.endpoint || 'No endpoint'}</span> · queue {item.queueDepth} · last transmission {formatTime(item.lastTransmission)}{item.nextRetryAt ? ` · retry ${formatTime(item.nextRetryAt)} (attempt ${item.reconnectAttempt})` : ''}</p>{item.lastError && <p className="mt-1 text-sm text-destructive">{item.lastError}</p>}</div><div className="flex flex-wrap justify-end gap-2"><Button variant="outline" size="sm" onClick={event => { event.stopPropagation(); navigate(`/operations/printer-logs?printerId=${encodeURIComponent(item.printer.id)}`) }}><ScrollText />Logs</Button><Button variant="outline" size="sm" onClick={event => { event.stopPropagation(); action.mutate({ path: `/printers/${encodeURIComponent(item.printer.id)}/test` }); toast.info(`Test print requested for ${item.printer.id}`) }}><PrinterIcon />Test</Button><Button variant="outline" size="sm" onClick={event => { event.stopPropagation(); action.mutate({ path: `/printers/${encodeURIComponent(item.printer.id)}/reconnect` }) }}><RefreshCw />Reconnect</Button></div></CardHeader>
      {!!item.attentionCount && <CardContent><p className="text-sm font-medium text-amber-700 dark:text-amber-300">{item.attentionCount} Print Run{item.attentionCount === 1 ? '' : 's'} need attention</p></CardContent>}
    </Card>)}</div>

    <Dialog open={!!selected} onOpenChange={open => !open && closeDetail()}><DialogContent className="max-h-[92vh] overflow-y-auto sm:max-w-5xl"><DialogHeader><DialogTitle className="flex items-center gap-2">{selected?.printer.displayName}{selected && <StatusBadge value={selected.state} />}</DialogTitle><DialogDescription>{selected?.printer.id} · {selected?.endpoint || 'No endpoint'}</DialogDescription></DialogHeader>
      {selected && <Tabs value={detailTab} onValueChange={changeTab}><TabsList><TabsTrigger value="overview">Overview</TabsTrigger><TabsTrigger value="queue">Queue</TabsTrigger><TabsTrigger value="logs">Logs</TabsTrigger></TabsList>
        <TabsContent value="overview" className="space-y-4"><div className="grid gap-3 rounded-xl border p-4 sm:grid-cols-2 lg:grid-cols-3">{[
          ['Printer ID', selected.printer.id], ['Connection', selected.state], ['Enabled', selected.printer.enabled ? 'Yes' : 'No'], ['Endpoint', selected.endpoint || selected.printer.endpoint], ['Device address', selected.printer.deviceAddress || '—'], ['Transport', selected.printer.transport], ['Queue depth', selected.queueDepth], ['Needs attention', selected.attentionCount], ['Last transmission', formatDate(selected.lastTransmission)], ['Next reconnect', selected.nextRetryAt ? `${formatDate(selected.nextRetryAt)} (attempt ${selected.reconnectAttempt || 1})` : '—'], ['Encoding', selected.printer.encoding], ['Characters per line', selected.printer.charactersPerLine], ['Serial settings', `${selected.printer.baudRate} baud · ${selected.printer.dataBits}/${selected.printer.parity}/${selected.printer.stopBits}`], ['Auto reconnect', selected.printer.autoReconnect ? 'Yes' : 'No'], ['Updated', formatDate(selected.printer.updatedAt)],
        ].map(([label, value]) => <div key={String(label)}><p className="text-xs text-muted-foreground">{label}</p><p className="break-words text-sm font-medium">{value}</p></div>)}</div>{selected.lastError && <p className="rounded-lg border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive">{selected.lastError}</p>}</TabsContent>
        <TabsContent value="queue" className="space-y-3"><div className="flex justify-end"><Button variant="outline" size="sm" onClick={() => navigate(`/operations/queue?printerId=${encodeURIComponent(selected.printer.id)}`)}><FileClock />Open full Queue</Button></div>{queue.isLoading && <LoadingState />}{queue.isError && <ErrorState error={queue.error} retry={() => queue.refetch()} />}{queue.data && <div className="overflow-x-auto rounded-xl border"><Table><TableHeader><TableRow><TableHead>Created</TableHead><TableHead>Run</TableHead><TableHead>Job</TableHead><TableHead>#</TableHead><TableHead>Trigger</TableHead><TableHead>Status</TableHead><TableHead>Error</TableHead><TableHead /></TableRow></TableHeader><TableBody>{allRuns(queue.data).map(run => <TableRow key={run.uid}><TableCell>{formatDate(run.createdAt)}</TableCell><TableCell className="font-mono text-xs">{run.uid}</TableCell><TableCell className="font-mono text-xs">{run.jobUid}</TableCell><TableCell>{run.runNumber}</TableCell><TableCell>{run.trigger}</TableCell><TableCell><StatusBadge value={run.status} /></TableCell><TableCell>{run.errorMessage || '—'}</TableCell><TableCell><Button size="sm" variant="outline" onClick={() => openJob(run.jobUid)}>View Job</Button></TableCell></TableRow>)}</TableBody></Table></div>}</TabsContent>
        <TabsContent value="logs" className="space-y-3"><div className="flex justify-end"><Button variant="outline" size="sm" onClick={() => navigate(`/operations/printer-logs?printerId=${encodeURIComponent(selected.printer.id)}`)}><ScrollText />Open full Printer Logs</Button></div>{logs.isLoading && <LoadingState />}{logs.isError && <ErrorState error={logs.error} retry={() => logs.refetch()} />}{logs.data && <div className="overflow-x-auto rounded-xl border"><Table><TableHeader><TableRow><TableHead>Time</TableHead><TableHead>Event</TableHead><TableHead>Run</TableHead><TableHead>Message</TableHead></TableRow></TableHeader><TableBody>{logs.data.events.map(entry => <TableRow key={entry.id}><TableCell>{formatDate(entry.createdAt)}</TableCell><TableCell>{entry.type}</TableCell><TableCell className="font-mono text-xs">{entry.runUid || '—'}</TableCell><TableCell>{entry.message || '—'}</TableCell></TableRow>)}</TableBody></Table></div>}</TabsContent>
      </Tabs>}
      <DialogFooter className="flex-wrap"><Button variant="outline" onClick={() => selected && action.mutate({ path: `/printers/${encodeURIComponent(selected.printer.id)}/test` })}><PrinterIcon />Test print</Button><Button variant="outline" onClick={() => selected && action.mutate({ path: `/printers/${encodeURIComponent(selected.printer.id)}/reconnect` })}><RefreshCw />Reconnect</Button><Button variant="outline" onClick={() => selected && openEditor(selected.printer)}><Pencil />Configure</Button><Button variant="outline" onClick={() => selected && action.mutate({ path: `/printers/${encodeURIComponent(selected.printer.id)}/${selected.printer.enabled ? 'disable' : 'enable'}` })}><Power />{selected?.printer.enabled ? 'Disable' : 'Enable'}</Button><Button variant="destructive" onClick={() => setRemoveOpen(true)}><Trash2 />Remove</Button></DialogFooter>
    </DialogContent></Dialog>

    <Dialog open={!!editor} onOpenChange={open => !open && setEditor(null)}><DialogContent className="sm:max-w-lg"><DialogHeader><DialogTitle>{editor?.editingId ? `Configure ${editor.id}` : 'Add printer'}</DialogTitle><DialogDescription>Choose the stable printer identity, discovered endpoint, and rendering profile.</DialogDescription></DialogHeader>{editor && <form id="printer-editor" className="space-y-4" onSubmit={event => { event.preventDefault(); save.mutate(editor) }}>
      <div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="printer-id">Printer ID</Label><Input id="printer-id" disabled={!!editor.editingId} required pattern="[a-z0-9][a-z0-9_-]{0,31}" value={editor.id} onChange={event => setEditor({ ...editor, id: event.target.value })} /></div><div className="space-y-2"><Label htmlFor="printer-name">Display name</Label><Input id="printer-name" value={editor.displayName} onChange={event => setEditor({ ...editor, displayName: event.target.value })} /></div></div>
      <div className="space-y-2"><div className="flex items-center justify-between"><Label htmlFor="printer-endpoint">Endpoint</Label><Button type="button" variant="ghost" size="sm" onClick={() => candidates.refetch()}><RefreshCw />Refresh</Button></div><select id="printer-endpoint" required className={selectClass} value={editor.endpoint} onChange={event => { const candidate = configuredCandidate(event.target.value); setEditor({ ...editor, endpoint: event.target.value, deviceAddress: candidate?.deviceAddress || editor.deviceAddress }) }}>{editor.endpoint && !candidates.data?.some(item => item.endpoint === editor.endpoint) && <option value={editor.endpoint}>{editor.endpoint}</option>}{candidates.data?.map(candidate => <option key={candidate.endpoint} value={candidate.endpoint}>{candidate.endpoint}{candidate.deviceName ? ` — ${candidate.deviceName}` : ''}{candidate.isPrinter ? ' · printer' : ''}</option>)}{!candidates.data?.length && <option value="">No endpoints found</option>}</select></div>
      <div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="printer-encoding">Encoding</Label><select id="printer-encoding" className={selectClass} value={editor.encoding} onChange={event => setEditor({ ...editor, encoding: event.target.value })}>{['CP858', 'CP437', 'CP850', 'Windows-1252'].map(value => <option key={value}>{value}</option>)}</select></div><div className="space-y-2"><Label htmlFor="printer-width">Characters per line</Label><Input id="printer-width" type="number" min={8} max={96} value={editor.charactersPerLine} onChange={event => setEditor({ ...editor, charactersPerLine: Number(event.target.value) })} /></div></div>
    </form>}<DialogFooter><Button type="submit" form="printer-editor" disabled={save.isPending}><Settings />{save.isPending ? 'Saving…' : 'Save printer'}</Button></DialogFooter></DialogContent></Dialog>

    <AlertDialog open={removeOpen} onOpenChange={setRemoveOpen}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Remove {selected?.printer.displayName}?</AlertDialogTitle><AlertDialogDescription>Existing Job history will be preserved. A printer with active or retry-pending Print Runs cannot be removed.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Back</AlertDialogCancel><AlertDialogAction variant="destructive" onClick={async () => { if (!selected) return; try { await api.mutate(`/printers/${encodeURIComponent(selected.printer.id)}`, 'DELETE'); toast.success(`${selected.printer.displayName} removed`); setRemoveOpen(false); closeDetail(); await invalidate() } catch (error) { toast.error(error instanceof Error ? error.message : 'Remove failed') } }}><Trash2 />Remove printer</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </>
}
